### ISSUE TITLE
Add multilanguage support

### ISSUE THREAD

**Issue by DominikBritz** [proxb/PinnedItem#1]
This is the best written pin to taskbar module out there! It would be nice if you add mulitlanguage support. The verb 'Pin To Taskbar' is only valid for an english os and will fail on e.g. a german system. Here is an example how to implement it https://gallery.technet.microsoft.com/ScriptCenter/b66434f1-4b3f-4a94-8dc3-e406eb30b750/

**Comment by proxb** [comment]
Thanks! I will definitely review the code and get it integrated with my module!

**Comment by proxb** [comment]
Ok, I added the multi-language support for this module and updated the module.
